// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Z9Flex.Client.Models;
namespace Z9Flex.Client.JsonEscaped.DoorModeChange
{
    /// <summary>
    /// Builds and executes requests for operations under \json\doorModeChange
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DoorModeChangeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DoorModeChangeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/json/doorModeChange{?tag*,unid*,uuid*,value*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DoorModeChangeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/json/doorModeChange{?tag*,unid*,uuid*,value*}", rawUrl)
        {
        }
        /// <summary>
        /// Door: mode change
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.VoidObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Z9Flex.Client.Models.VoidObject?> GetAsync(Action<RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder.DoorModeChangeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Z9Flex.Client.Models.VoidObject> GetAsync(Action<RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder.DoorModeChangeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Z9Flex.Client.Models.VoidObject>(requestInfo, global::Z9Flex.Client.Models.VoidObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Door: mode change
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder.DoorModeChangeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder.DoorModeChangeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Door: mode change
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DoorModeChangeRequestBuilderGetQueryParameters 
        {
            /// <summary>Device tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tag")]
            public string? Tag { get; set; }
#nullable restore
#else
            [QueryParameter("tag")]
            public string Tag { get; set; }
#endif
            /// <summary>Device unique ID</summary>
            [QueryParameter("unid")]
            public int? Unid { get; set; }
            /// <summary>Device UUID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("uuid")]
            public string? Uuid { get; set; }
#nullable restore
#else
            [QueryParameter("uuid")]
            public string Uuid { get; set; }
#endif
            /// <summary>Door mode type, or &quot;RESET&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("value")]
            public string? Value { get; set; }
#nullable restore
#else
            [QueryParameter("value")]
            public string Value { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DoorModeChangeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder.DoorModeChangeRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
