// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// Information returned from an /authenticate call, including whether authentication was successful or not, and the session token if successful.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthenticateResult : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>API version - major version number changes potentially break backwards compatibility, minor version changes do not.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiVersion { get; set; }
#nullable restore
#else
        public string ApiVersion { get; set; }
#endif
        /// <summary>true if authentication succeeded, false otherwise.</summary>
        public bool? Authenticated { get; set; }
        /// <summary>A reference (really a summary) from an Evt to a Dev, containing its essential properties, and without requiring any lookup of the referenced object for reporting, filtering, or display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.EvtDevRef? EvtDevRef { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.EvtDevRef EvtDevRef { get; set; }
#endif
        /// <summary>The session token to be used in subsequent API calls</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionToken { get; set; }
#nullable restore
#else
        public string SessionToken { get; set; }
#endif
        /// <summary>Software version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoftwareVersion { get; set; }
#nullable restore
#else
        public string SoftwareVersion { get; set; }
#endif
        /// <summary>Build timestamp of the software version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoftwareVersionTimestamp { get; set; }
#nullable restore
#else
        public string SoftwareVersionTimestamp { get; set; }
#endif
        /// <summary>Time zone of the server/panel logged into.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.AuthenticateResult"/> and sets the default values.
        /// </summary>
        public AuthenticateResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.AuthenticateResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.AuthenticateResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.AuthenticateResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apiVersion", n => { ApiVersion = n.GetStringValue(); } },
                { "authenticated", n => { Authenticated = n.GetBoolValue(); } },
                { "evtDevRef", n => { EvtDevRef = n.GetObjectValue<global::Z9Flex.Client.Models.EvtDevRef>(global::Z9Flex.Client.Models.EvtDevRef.CreateFromDiscriminatorValue); } },
                { "sessionToken", n => { SessionToken = n.GetStringValue(); } },
                { "softwareVersion", n => { SoftwareVersion = n.GetStringValue(); } },
                { "softwareVersionTimestamp", n => { SoftwareVersionTimestamp = n.GetStringValue(); } },
                { "timeZone", n => { TimeZone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("apiVersion", ApiVersion);
            writer.WriteBoolValue("authenticated", Authenticated);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.EvtDevRef>("evtDevRef", EvtDevRef);
            writer.WriteStringValue("sessionToken", SessionToken);
            writer.WriteStringValue("softwareVersion", SoftwareVersion);
            writer.WriteStringValue("softwareVersionTimestamp", SoftwareVersionTimestamp);
            writer.WriteStringValue("timeZone", TimeZone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
