// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// The simplest form of a DataLayout which has only a single DataFormat.  There is no need to specify the location of this data, as there is only one.  So for ABA Track II magnetic strip cards, or non-smart proximity/RFID cards, this simply corresponds to all the encoded data on the card in one chunk. - only applicable if layoutType=0 (DataLayoutType_BASIC)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BasicDataLayout : global::Z9Flex.Client.Models.DataLayout, IParsable
    {
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? DataFormat { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef DataFormat { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.BasicDataLayout"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Z9Flex.Client.Models.BasicDataLayout CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.BasicDataLayout();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "dataFormat", n => { DataFormat = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("dataFormat", DataFormat);
        }
    }
}
#pragma warning restore CS0618
