// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// Element of a BinaryFormat.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BinaryElement : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Length in bits.</summary>
        public int? Len { get; set; }
        /// <summary>Ordering for the purposes of processing. Not necessarily the same as the physical order on the card/credential.</summary>
        public int? Num { get; set; }
        /// <summary>Starting bit, 0-based.</summary>
        public int? Start { get; set; }
        /// <summary>Type (subclass) of BinaryElement.0 - STATIC - Static (fixed) element - StaticBinaryElement.1 - PARITY - Parity - ParityBinaryElement.2 - FIELD - Data field - FieldBinaryElement.</summary>
        public int? Type { get; set; }
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.BinaryElement"/> and sets the default values.
        /// </summary>
        public BinaryElement()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.BinaryElement"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.BinaryElement CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            return mappingValue switch
            {
                "0" => new global::Z9Flex.Client.Models.StaticBinaryElement(),
                "1" => new global::Z9Flex.Client.Models.ParityBinaryElement(),
                "2" => new global::Z9Flex.Client.Models.FieldBinaryElement(),
                _ => new global::Z9Flex.Client.Models.BinaryElement(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "len", n => { Len = n.GetIntValue(); } },
                { "num", n => { Num = n.GetIntValue(); } },
                { "start", n => { Start = n.GetIntValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("len", Len);
            writer.WriteIntValue("num", Num);
            writer.WriteIntValue("start", Start);
            writer.WriteIntValue("type", Type);
            writer.WriteIntValue("unid", Unid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
