// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// Binary DataFormat, used for Prox/Wiegand card formats.  It contains an element for each field, parity bit, etc. - only applicable if dataFormatType=1 (DataFormatType_BINARY)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BinaryFormat : global::Z9Flex.Client.Models.DataFormat, IParsable
    {
        /// <summary>Elements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Z9Flex.Client.Models.BinaryElement>? Elements { get; set; }
#nullable restore
#else
        public List<global::Z9Flex.Client.Models.BinaryElement> Elements { get; set; }
#endif
        /// <summary>Maximum number of bits. Generally the same as minBits.</summary>
        public int? MaxBits { get; set; }
        /// <summary>Minimum number of bits.</summary>
        public int? MinBits { get; set; }
        /// <summary>Whether reverse read is supported.  If true, a normal read is checked to see if it matches the format, and then the reversed bits are tried.</summary>
        public bool? SupportReverseRead { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.BinaryFormat"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Z9Flex.Client.Models.BinaryFormat CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.BinaryFormat();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "elements", n => { Elements = n.GetCollectionOfObjectValues<global::Z9Flex.Client.Models.BinaryElement>(global::Z9Flex.Client.Models.BinaryElement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "maxBits", n => { MaxBits = n.GetIntValue(); } },
                { "minBits", n => { MinBits = n.GetIntValue(); } },
                { "supportReverseRead", n => { SupportReverseRead = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::Z9Flex.Client.Models.BinaryElement>("elements", Elements);
            writer.WriteIntValue("maxBits", MaxBits);
            writer.WriteIntValue("minBits", MinBits);
            writer.WriteBoolValue("supportReverseRead", SupportReverseRead);
        }
    }
}
#pragma warning restore CS0618
