// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// A template for Card/PIN (CardPin)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CardPinTemplate : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If true, then any DataLayout is supported.  This allows modeling of systems which do not link credentials to formats.  If this option is used with drivers for hardware that do require this link, then the first available DataLayout is to be used.</summary>
        public bool? AnyDataLayout { get; set; }
        /// <summary>The presence of a CredComponent.0 - ABSENT - Absent.1 - REQUIRED - Required.2 - OPTIONAL - Optional.</summary>
        public int? CredComponentPresence { get; set; }
        /// <summary>The presence of a CredComponent.0 - ABSENT - Absent.1 - REQUIRED - Required.2 - OPTIONAL - Optional.</summary>
        public int? CredNumPresence { get; set; }
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? DataLayout { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef DataLayout { get; set; }
#endif
        /// <summary>Facility code (AKA site code, building code).</summary>
        public int? FacilityCode { get; set; }
        /// <summary>Maximum PIN length.</summary>
        public int? MaxPinLength { get; set; }
        /// <summary>Minimum PIN length.</summary>
        public int? MinPinLength { get; set; }
        /// <summary>The presence of a CredComponent.0 - ABSENT - Absent.1 - REQUIRED - Required.2 - OPTIONAL - Optional.</summary>
        public int? PinPresence { get; set; }
        /// <summary>null if optional, true if required to be unique in Cred, false if required to be set as not unique in Cred.</summary>
        public bool? PinUnique { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.CardPinTemplate"/> and sets the default values.
        /// </summary>
        public CardPinTemplate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.CardPinTemplate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.CardPinTemplate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.CardPinTemplate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "anyDataLayout", n => { AnyDataLayout = n.GetBoolValue(); } },
                { "credComponentPresence", n => { CredComponentPresence = n.GetIntValue(); } },
                { "credNumPresence", n => { CredNumPresence = n.GetIntValue(); } },
                { "dataLayout", n => { DataLayout = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "facilityCode", n => { FacilityCode = n.GetIntValue(); } },
                { "maxPinLength", n => { MaxPinLength = n.GetIntValue(); } },
                { "minPinLength", n => { MinPinLength = n.GetIntValue(); } },
                { "pinPresence", n => { PinPresence = n.GetIntValue(); } },
                { "pinUnique", n => { PinUnique = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("anyDataLayout", AnyDataLayout);
            writer.WriteIntValue("credComponentPresence", CredComponentPresence);
            writer.WriteIntValue("credNumPresence", CredNumPresence);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("dataLayout", DataLayout);
            writer.WriteIntValue("facilityCode", FacilityCode);
            writer.WriteIntValue("maxPinLength", MaxPinLength);
            writer.WriteIntValue("minPinLength", MinPinLength);
            writer.WriteIntValue("pinPresence", PinPresence);
            writer.WriteBoolValue("pinUnique", PinUnique);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
