// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// A card and/or PIN.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CardPin : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>big integer, represented as a string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CredNum { get; set; }
#nullable restore
#else
        public string CredNum { get; set; }
#endif
        /// <summary>Facility code (AKA site code, building code). Normally, facility code is specified on the CredTemplate (CardPinTemplate).  But in cases where the facility code is not part of the template, it can be specified here.</summary>
        public int? FacilityCode { get; set; }
        /// <summary>PIN (Personal Identification Number).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pin { get; set; }
#nullable restore
#else
        public string Pin { get; set; }
#endif
        /// <summary>Whether the PIN is unique.  This is more often set to true than not, to allow PIN-only access.</summary>
        public bool? PinUnique { get; set; }
        /// <summary>Registration code, used for certain mobile credential technologies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegistrationCode { get; set; }
#nullable restore
#else
        public string RegistrationCode { get; set; }
#endif
        /// <summary>Registration URL, used for certain mobile credential technologies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegistrationUrl { get; set; }
#nullable restore
#else
        public string RegistrationUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.CardPin"/> and sets the default values.
        /// </summary>
        public CardPin()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.CardPin"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.CardPin CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.CardPin();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "credNum", n => { CredNum = n.GetStringValue(); } },
                { "facilityCode", n => { FacilityCode = n.GetIntValue(); } },
                { "pin", n => { Pin = n.GetStringValue(); } },
                { "pinUnique", n => { PinUnique = n.GetBoolValue(); } },
                { "registrationCode", n => { RegistrationCode = n.GetStringValue(); } },
                { "registrationUrl", n => { RegistrationUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("credNum", CredNum);
            writer.WriteIntValue("facilityCode", FacilityCode);
            writer.WriteStringValue("pin", Pin);
            writer.WriteBoolValue("pinUnique", PinUnique);
            writer.WriteStringValue("registrationCode", RegistrationCode);
            writer.WriteStringValue("registrationUrl", RegistrationUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
