// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// DevConfig for a CredReader
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CredReaderConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Possible communications types for a CredReader.6 - OSDP_HALF_DUPLEX - OSDP, half-duplex.  This is &quot;normal&quot; OSDP.</summary>
        public int? CommType { get; set; }
        /// <summary>Used for communications where connection initiation direction is configurable.  Most commonly used for TCP connections, where the Dev may be either the &quot;client&quot; or &quot;server&quot; end of the socket.</summary>
        public bool? DevInitiatesConnection { get; set; }
        /// <summary>Disable encryption, generally for OSDP readers/subcontrollers that would otherwise be using Secure Channel.  Intended to be used for diagnostics only, not recommended for production.</summary>
        public bool? DisableEncryption { get; set; }
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? EncryptionKeyRef { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef EncryptionKeyRef { get; set; }
#endif
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? EncryptionKeyRefNext { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef EncryptionKeyRefNext { get; set; }
#endif
        /// <summary>Possible LED types for a CredReader.2 - OSDP - OSDP - this is more or less implied by CredReaderCommType.OSDP.</summary>
        public int? LedType { get; set; }
        /// <summary>password to connect to the device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>Serial port address for this reader.  If set, this is used as the serial port address instead of Dev.address.  May be a literal serial port address like /dev/ttyUSB0, COM1, etc, or, an ordinal such as 0 or 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SerialPortAddress { get; set; }
#nullable restore
#else
        public string SerialPortAddress { get; set; }
#endif
        /// <summary>Possible tamper communication types for a CredReader.2 - OSDP - OSDP - this is more or less implied by CredReaderCommType.OSDP.</summary>
        public int? TamperType { get; set; }
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>username to connect to the device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>Version (for optimistic locking)</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.CredReaderConfig"/> and sets the default values.
        /// </summary>
        public CredReaderConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.CredReaderConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.CredReaderConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.CredReaderConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commType", n => { CommType = n.GetIntValue(); } },
                { "devInitiatesConnection", n => { DevInitiatesConnection = n.GetBoolValue(); } },
                { "disableEncryption", n => { DisableEncryption = n.GetBoolValue(); } },
                { "encryptionKeyRef", n => { EncryptionKeyRef = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "encryptionKeyRefNext", n => { EncryptionKeyRefNext = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "ledType", n => { LedType = n.GetIntValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "serialPortAddress", n => { SerialPortAddress = n.GetStringValue(); } },
                { "tamperType", n => { TamperType = n.GetIntValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("commType", CommType);
            writer.WriteBoolValue("devInitiatesConnection", DevInitiatesConnection);
            writer.WriteBoolValue("disableEncryption", DisableEncryption);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("encryptionKeyRef", EncryptionKeyRef);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("encryptionKeyRefNext", EncryptionKeyRefNext);
            writer.WriteIntValue("ledType", LedType);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("serialPortAddress", SerialPortAddress);
            writer.WriteIntValue("tamperType", TamperType);
            writer.WriteIntValue("unid", Unid);
            writer.WriteStringValue("username", Username);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
