// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// A credential - for door access and/or application access.  May include various factors such as card number/PIN, biometric data, username/password.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Cred : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A card and/or PIN.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.CardPin? CardPin { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.CardPin CardPin { get; set; }
#endif
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? CredTemplate { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef CredTemplate { get; set; }
#endif
        /// <summary>Modifiers to a Cred, CredHolder, or a PrivBinding for Door access.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.DoorAccessModifiers? DoorAccessModifiers { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.DoorAccessModifiers DoorAccessModifiers { get; set; }
#endif
        /// <summary>Effective date - credential inactive before this date.</summary>
        public DateTimeOffset? Effective { get; set; }
        /// <summary>Whether this credential is enabled (active), or not.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Expiration date - credential inactive after this date.</summary>
        public DateTimeOffset? Expires { get; set; }
        /// <summary>Name as a single string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Privilege bindings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Z9Flex.Client.Models.CredPrivBinding>? PrivBindings { get; set; }
#nullable restore
#else
        public List<global::Z9Flex.Client.Models.CredPrivBinding> PrivBindings { get; set; }
#endif
        /// <summary>tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>UUID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>Version (for optimistic locking)</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.Cred"/> and sets the default values.
        /// </summary>
        public Cred()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.Cred"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.Cred CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.Cred();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cardPin", n => { CardPin = n.GetObjectValue<global::Z9Flex.Client.Models.CardPin>(global::Z9Flex.Client.Models.CardPin.CreateFromDiscriminatorValue); } },
                { "credTemplate", n => { CredTemplate = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "doorAccessModifiers", n => { DoorAccessModifiers = n.GetObjectValue<global::Z9Flex.Client.Models.DoorAccessModifiers>(global::Z9Flex.Client.Models.DoorAccessModifiers.CreateFromDiscriminatorValue); } },
                { "effective", n => { Effective = n.GetDateTimeOffsetValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "expires", n => { Expires = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "privBindings", n => { PrivBindings = n.GetCollectionOfObjectValues<global::Z9Flex.Client.Models.CredPrivBinding>(global::Z9Flex.Client.Models.CredPrivBinding.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Z9Flex.Client.Models.CardPin>("cardPin", CardPin);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("credTemplate", CredTemplate);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.DoorAccessModifiers>("doorAccessModifiers", DoorAccessModifiers);
            writer.WriteDateTimeOffsetValue("effective", Effective);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteDateTimeOffsetValue("expires", Expires);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Z9Flex.Client.Models.CredPrivBinding>("privBindings", PrivBindings);
            writer.WriteStringValue("tag", Tag);
            writer.WriteIntValue("unid", Unid);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
