// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// Data layout of DataFormat on a Cred.  This is most meaningful for smart cards (SmartDataLayout), which can have multiple files/sectors/blocks of data, protected by keys.  ANSI/ISO ABA Track II Magnetic stripe and non-smart-card proximity/RFID cards (binary/Wiegand) use the subclass BasicDataLayout, which simply has a single DataFormat, corresponding to all the data on the card.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataLayout : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the DataLayout is active (enabled) or not.  if null, this should be interpreted as true (enabled).</summary>
        public bool? Enabled { get; set; }
        /// <summary>The type of a DataLayout.0 - BASIC - Basic - only has one data format (DataFormat).</summary>
        public int? LayoutType { get; set; }
        /// <summary>Name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Priority.  Determines the order in which multiple DataLayout are applied at card read time.</summary>
        public int? Priority { get; set; }
        /// <summary>tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>UUID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>Version (for optimistic locking)</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.DataLayout"/> and sets the default values.
        /// </summary>
        public DataLayout()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.DataLayout"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.DataLayout CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("layoutType")?.GetStringValue();
            return mappingValue switch
            {
                "0" => new global::Z9Flex.Client.Models.BasicDataLayout(),
                _ => new global::Z9Flex.Client.Models.DataLayout(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "layoutType", n => { LayoutType = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteIntValue("layoutType", LayoutType);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("priority", Priority);
            writer.WriteStringValue("tag", Tag);
            writer.WriteIntValue("unid", Unid);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
