// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// Base class for a device - a hardware (or in some cases software, or virtual) component within the system, arranged in a physical and logical hierarchy.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Dev : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The hardware/network address of this device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>The commFamily property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CommFamily { get; set; }
#nullable restore
#else
        public UntypedNode CommFamily { get; set; }
#endif
        /// <summary>Model for a Dev (device).0 - IO_CONTROLLER_Z9_CUSTOM - IO_CONTROLLER model - z9io - Custom.14 - SENSOR_DIGITAL - SENSOR model - digital.18 - ACTUATOR_DIGITAL - ACTUATOR model - digital.26 - IO_CONTROLLER_Z9_SPCORE - IO_CONTROLLER - Z9-Security SP-Core.46 - IO_CONTROLLER_EXTERNAL - Externally-defined - IO_CONTROLLER.164 - IO_CONTROLLER_COMMUNITY - IO_CONTROLLER model - Community.165 - IO_CONTROLLER_COMMUNITY_SUB - IO_CONTROLLER model - Community sub-controller.227 - CRED_READER_OSDP - CRED_READER model - OSDP (generic).259 - DOOR_COMMUNITY - DOOR model - Community.</summary>
        public int? DevMod { get; set; }
        /// <summary>DevMod-specific configuration for a Dev. Subclasses correspond to different DevMod values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.DevModConfig? DevModConfig { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.DevModConfig DevModConfig { get; set; }
#endif
        /// <summary>Device hardware platform, or family, for a device model (DevMod) for a Dev.0 - Z9_SECURITY - Z9 Security, including Z9/Open and Z9/Flex.9 - EXTERNAL - External.11 - PKOC - PKOC.17 - COMMUNITY - Community.19 - PSIA - PSIA.</summary>
        public int? DevPlatform { get; set; }
        /// <summary>Device sub-type.7 - IO_CONTROLLER_SUB - IO_CONTROLLER - sub-controller.</summary>
        public int? DevSubType { get; set; }
        /// <summary>Type (subclass) of Dev (device).0 - NODE_DEV - Device representing a node, which is a server or service running the Z9/FL=X software.1 - IO_CONTROLLER - A controller, such as an access control panel.  It may be an intelligent controller, a downstream controller, or a virtual/placeholder controller.2 - SENSOR - Sensor (input), including door contact and REX inputs, AUX inputs, alarm inputs, environmental inputs, others.3 - ACTUATOR - Actuator (output), including relay outputs, AUX outputs, LED outputs, others.4 - CRED_READER - Credential reader.5 - DOOR - Access-control door (access point).</summary>
        public int? DevType { get; set; }
        /// <summary>Usage of a Dev.  This describes how the device is used, in other words, its function.0 - ACTUATOR_DOOR_STRIKE - ACTUATOR - door strike. HAS SEMANTICS.2 - ACTUATOR_CRED_READER_LED_RED - ACTUATOR - Cred reader LED - Red. HAS SEMANTICS.3 - ACTUATOR_CRED_READER_LED_GREEN - ACTUATOR - Cred reader LED - Green. HAS SEMANTICS.4 - ACTUATOR_CRED_READER_BEEPER - ACTUATOR - Cred reader beeper. HAS SEMANTICS.10 - SENSOR_DOOR_CONTACT - SENSOR - door contact. HAS SEMANTICS.11 - SENSOR_REX - SENSOR - REX (request to exit). HAS SEMANTICS.12 - SENSOR_TAMPER - SENSOR - Tamper. HAS SEMANTICS.13 - SENSOR_POWER - SENSOR - Power monitor. HAS SEMANTICS.14 - SENSOR_BATTERY - SENSOR - Battery monitor. HAS SEMANTICS.38 - CRED_READER_DOOR - CRED_READER - for a door.  HAS SEMANTICS.39 - DOOR_EXIT - DOOR - exit (as opposed to entry). HAS SEMANTICS.  Logical parent must be a DOOR.44 - IO_CONTROLLER_SECONDARY - IO_CONTROLLER - secondary. HAS SEMANTICS.</summary>
        public int? DevUse { get; set; }
        /// <summary>true if the device is enabled, false if disabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>The externalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>Whether to ignore daylight savings.</summary>
        public bool? IgnoreDaylightSavings { get; set; }
        /// <summary>Logical address, if different from physical address.</summary>
        public int? LogicalAddress { get; set; }
        /// <summary>Reference to (and &apos;type&apos; equals) - Dev - or subclass - Logical children devices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Z9Flex.Client.Models.ObjRef>? LogicalChildren { get; set; }
#nullable restore
#else
        public List<global::Z9Flex.Client.Models.ObjRef> LogicalChildren { get; set; }
#endif
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? LogicalParent { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef LogicalParent { get; set; }
#endif
        /// <summary>MAC address (if applicable).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MacAddress { get; set; }
#nullable restore
#else
        public string MacAddress { get; set; }
#endif
        /// <summary>Name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Reference to (and &apos;type&apos; equals) - Dev - or subclass - Physical children devices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Z9Flex.Client.Models.ObjRef>? PhysicalChildren { get; set; }
#nullable restore
#else
        public List<global::Z9Flex.Client.Models.ObjRef> PhysicalChildren { get; set; }
#endif
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? PhysicalParent { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef PhysicalParent { get; set; }
#endif
        /// <summary>Port number.  For network-connected devices, this is generally a TCP port.  For serially-connected devices, this is often a polling address.</summary>
        public int? Port { get; set; }
        /// <summary>Connection speed.  Generally for serially-connected devices.</summary>
        public int? Speed { get; set; }
        /// <summary>tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>Time zone the device is in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>UUID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>Version (for optimistic locking)</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.Dev"/> and sets the default values.
        /// </summary>
        public Dev()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.Dev"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.Dev CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("devType")?.GetStringValue();
            return mappingValue switch
            {
                "0" => new global::Z9Flex.Client.Models.NodeDev(),
                "1" => new global::Z9Flex.Client.Models.Controller(),
                "2" => new global::Z9Flex.Client.Models.Sensor(),
                "3" => new global::Z9Flex.Client.Models.Actuator(),
                "4" => new global::Z9Flex.Client.Models.CredReader(),
                "5" => new global::Z9Flex.Client.Models.Door(),
                _ => new global::Z9Flex.Client.Models.Dev(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "commFamily", n => { CommFamily = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "devMod", n => { DevMod = n.GetIntValue(); } },
                { "devModConfig", n => { DevModConfig = n.GetObjectValue<global::Z9Flex.Client.Models.DevModConfig>(global::Z9Flex.Client.Models.DevModConfig.CreateFromDiscriminatorValue); } },
                { "devPlatform", n => { DevPlatform = n.GetIntValue(); } },
                { "devSubType", n => { DevSubType = n.GetIntValue(); } },
                { "devType", n => { DevType = n.GetIntValue(); } },
                { "devUse", n => { DevUse = n.GetIntValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "ignoreDaylightSavings", n => { IgnoreDaylightSavings = n.GetBoolValue(); } },
                { "logicalAddress", n => { LogicalAddress = n.GetIntValue(); } },
                { "logicalChildren", n => { LogicalChildren = n.GetCollectionOfObjectValues<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "logicalParent", n => { LogicalParent = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "macAddress", n => { MacAddress = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "physicalChildren", n => { PhysicalChildren = n.GetCollectionOfObjectValues<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "physicalParent", n => { PhysicalParent = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "port", n => { Port = n.GetIntValue(); } },
                { "speed", n => { Speed = n.GetIntValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "timeZone", n => { TimeZone = n.GetStringValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteObjectValue<UntypedNode>("commFamily", CommFamily);
            writer.WriteIntValue("devMod", DevMod);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.DevModConfig>("devModConfig", DevModConfig);
            writer.WriteIntValue("devPlatform", DevPlatform);
            writer.WriteIntValue("devSubType", DevSubType);
            writer.WriteIntValue("devType", DevType);
            writer.WriteIntValue("devUse", DevUse);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteBoolValue("ignoreDaylightSavings", IgnoreDaylightSavings);
            writer.WriteIntValue("logicalAddress", LogicalAddress);
            writer.WriteCollectionOfObjectValues<global::Z9Flex.Client.Models.ObjRef>("logicalChildren", LogicalChildren);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("logicalParent", LogicalParent);
            writer.WriteStringValue("macAddress", MacAddress);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Z9Flex.Client.Models.ObjRef>("physicalChildren", PhysicalChildren);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("physicalParent", PhysicalParent);
            writer.WriteIntValue("port", Port);
            writer.WriteIntValue("speed", Speed);
            writer.WriteStringValue("tag", Tag);
            writer.WriteStringValue("timeZone", TimeZone);
            writer.WriteIntValue("unid", Unid);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
