// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// The state of a single DevAspect for a Dev.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DevAspectState : IAdditionalDataHolder, IParsable
    {
        /// <summary>Activity state of a Dev (generally Sensor or Actuator) - whether it is active or inactive, but also includes warning, and repeating pulse.0 - INACTIVE - Inactive, off.1 - ACTIVE - Active, on.</summary>
        public int? ActivityState { get; set; }
        /// <summary>If true, corresponding property is stale - activityState</summary>
        public bool? ActivityStateStale { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Communications state of a Dev - online/offline.0 - OFFLINE - Offline.1 - ONLINE - Online.</summary>
        public int? CommState { get; set; }
        /// <summary>If true, corresponding property is stale - commState</summary>
        public bool? CommStateStale { get; set; }
        /// <summary>Time recorded in DB.  Stored in server local time.  Presentation time zone is the time zone of the server.</summary>
        public DateTimeOffset? DbTime { get; set; }
        /// <summary>An aspect of the state of a Dev.0 - PRIMARY - Primary aspect.  Most devices only have a single aspect, this one.5 - DOOR_FORCED - Door - forced.6 - DOOR_HELD - Door - held.15 - DOOR_UNLOCKED - Door - unlocked.16 - DOOR_OPEN - Door - open.</summary>
        public int? DevAspect { get; set; }
        /// <summary>A door mode.  Can specify whether access is allowed by unique PIN, as well as with card, and whether a confirming PIN is required when using a card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.DoorMode? DoorMode { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.DoorMode DoorMode { get; set; }
#endif
        /// <summary>If true, corresponding property is stale - doorMode</summary>
        public bool? DoorModeStale { get; set; }
        /// <summary>Externally-defined state text (presentable to a user).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalState { get; set; }
#nullable restore
#else
        public string ExternalState { get; set; }
#endif
        /// <summary>If true, corresponding property is stale - externalState</summary>
        public bool? ExternalStateStale { get; set; }
        /// <summary>Time occurred at hardware.  Stored in server local time.  Presentation time zone is determined by getTimeZone().</summary>
        public DateTimeOffset? HwTime { get; set; }
        /// <summary>Tamper state of a Dev.0 - NORMAL - Normal.1 - TAMPER - Tamper.</summary>
        public int? TamperState { get; set; }
        /// <summary>If true, corresponding property is stale - tamperState</summary>
        public bool? TamperStateStale { get; set; }
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.DevAspectState"/> and sets the default values.
        /// </summary>
        public DevAspectState()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.DevAspectState"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.DevAspectState CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.DevAspectState();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activityState", n => { ActivityState = n.GetIntValue(); } },
                { "activityStateStale", n => { ActivityStateStale = n.GetBoolValue(); } },
                { "commState", n => { CommState = n.GetIntValue(); } },
                { "commStateStale", n => { CommStateStale = n.GetBoolValue(); } },
                { "dbTime", n => { DbTime = n.GetDateTimeOffsetValue(); } },
                { "devAspect", n => { DevAspect = n.GetIntValue(); } },
                { "doorMode", n => { DoorMode = n.GetObjectValue<global::Z9Flex.Client.Models.DoorMode>(global::Z9Flex.Client.Models.DoorMode.CreateFromDiscriminatorValue); } },
                { "doorModeStale", n => { DoorModeStale = n.GetBoolValue(); } },
                { "externalState", n => { ExternalState = n.GetStringValue(); } },
                { "externalStateStale", n => { ExternalStateStale = n.GetBoolValue(); } },
                { "hwTime", n => { HwTime = n.GetDateTimeOffsetValue(); } },
                { "tamperState", n => { TamperState = n.GetIntValue(); } },
                { "tamperStateStale", n => { TamperStateStale = n.GetBoolValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("activityState", ActivityState);
            writer.WriteBoolValue("activityStateStale", ActivityStateStale);
            writer.WriteIntValue("commState", CommState);
            writer.WriteBoolValue("commStateStale", CommStateStale);
            writer.WriteDateTimeOffsetValue("dbTime", DbTime);
            writer.WriteIntValue("devAspect", DevAspect);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.DoorMode>("doorMode", DoorMode);
            writer.WriteBoolValue("doorModeStale", DoorModeStale);
            writer.WriteStringValue("externalState", ExternalState);
            writer.WriteBoolValue("externalStateStale", ExternalStateStale);
            writer.WriteDateTimeOffsetValue("hwTime", HwTime);
            writer.WriteIntValue("tamperState", TamperState);
            writer.WriteBoolValue("tamperStateStale", TamperStateStale);
            writer.WriteIntValue("unid", Unid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
