// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// An association of a Dev with its DevState.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DevStateRecord : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? Dev { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef Dev { get; set; }
#endif
        /// <summary>The state of a Dev, including all DevAspect.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.DevState? DevState { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.DevState DevState { get; set; }
#endif
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.DevStateRecord"/> and sets the default values.
        /// </summary>
        public DevStateRecord()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.DevStateRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.DevStateRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.DevStateRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dev", n => { Dev = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "devState", n => { DevState = n.GetObjectValue<global::Z9Flex.Client.Models.DevState>(global::Z9Flex.Client.Models.DevState.CreateFromDiscriminatorValue); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("dev", Dev);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.DevState>("devState", DevState);
            writer.WriteIntValue("unid", Unid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
