// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// A door mode.  Can specify whether access is allowed by unique PIN, as well as with card, and whether a confirming PIN is required when using a card.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DoorMode : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to allow access by card. If null, use system default.</summary>
        public bool? AllowCard { get; set; }
        /// <summary>Whether to allow access by unique PIN in CardPin. If null, use system default.</summary>
        public bool? AllowUniquePin { get; set; }
        /// <summary>Whether to require confirming PIN for access by card. If null, use system default.</summary>
        public bool? RequireConfirmingPinWithCard { get; set; }
        /// <summary>Values for static state of DoorMode.0 - LOCKED - Always locked, no access.1 - UNLOCKED - Always unlocked.2 - ACCESS_CONTROLLED - Normally locked (secure) but available for access-controlled entry.</summary>
        public int? StaticState { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.DoorMode"/> and sets the default values.
        /// </summary>
        public DoorMode()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.DoorMode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.DoorMode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.DoorMode();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowCard", n => { AllowCard = n.GetBoolValue(); } },
                { "allowUniquePin", n => { AllowUniquePin = n.GetBoolValue(); } },
                { "requireConfirmingPinWithCard", n => { RequireConfirmingPinWithCard = n.GetBoolValue(); } },
                { "staticState", n => { StaticState = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowCard", AllowCard);
            writer.WriteBoolValue("allowUniquePin", AllowUniquePin);
            writer.WriteBoolValue("requireConfirmingPinWithCard", RequireConfirmingPinWithCard);
            writer.WriteIntValue("staticState", StaticState);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
