// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// DevConfig for a Door.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DoorConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>True if the REX is not physically linked to the strike, and therefore the controller needs to activate the strike on REX. In many cases, the REX signal simply indicates that the user has unlocked the door from the inside, and the strike does not need to be involved. For example, many crash bars for exit, and electrified locksets work this way. In other cases, for convenience or fire code compliance, the REX directly unlocks the door electrically, by, for example, cutting the power to a mag lock.</summary>
        public bool? ActivateStrikeOnRex { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A door mode.  Can specify whether access is allowed by unique PIN, as well as with card, and whether a confirming PIN is required when using a card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.DoorMode? DefaultDoorMode { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.DoorMode DefaultDoorMode { get; set; }
#endif
        /// <summary>Used for communications where connection initiation direction is configurable.  Most commonly used for TCP connections, where the Dev may be either the &quot;client&quot; or &quot;server&quot; end of the socket.</summary>
        public bool? DevInitiatesConnection { get; set; }
        /// <summary>Disable encryption, generally for OSDP readers/subcontrollers that would otherwise be using Secure Channel.  Intended to be used for diagnostics only, not recommended for production.</summary>
        public bool? DisableEncryption { get; set; }
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? EncryptionKeyRef { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef EncryptionKeyRef { get; set; }
#endif
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? EncryptionKeyRefNext { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef EncryptionKeyRefNext { get; set; }
#endif
        /// <summary>The time in milliseconds after which the door is considered held open - extended (for disabled users, for example).</summary>
        public int? ExtendedHeldTime { get; set; }
        /// <summary>The time in milliseconds to activate the door strike - extended (for disabled users, for example).</summary>
        public int? ExtendedStrikeTime { get; set; }
        /// <summary>The time in milliseconds after which the door is considered held open.</summary>
        public int? HeldTime { get; set; }
        /// <summary>password to connect to the device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>The time in milliseconds to activate the door strike.</summary>
        public int? StrikeTime { get; set; }
        /// <summary>username to connect to the device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>Version (for optimistic locking)</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.DoorConfig"/> and sets the default values.
        /// </summary>
        public DoorConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.DoorConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.DoorConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.DoorConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activateStrikeOnRex", n => { ActivateStrikeOnRex = n.GetBoolValue(); } },
                { "defaultDoorMode", n => { DefaultDoorMode = n.GetObjectValue<global::Z9Flex.Client.Models.DoorMode>(global::Z9Flex.Client.Models.DoorMode.CreateFromDiscriminatorValue); } },
                { "devInitiatesConnection", n => { DevInitiatesConnection = n.GetBoolValue(); } },
                { "disableEncryption", n => { DisableEncryption = n.GetBoolValue(); } },
                { "encryptionKeyRef", n => { EncryptionKeyRef = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "encryptionKeyRefNext", n => { EncryptionKeyRefNext = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "extendedHeldTime", n => { ExtendedHeldTime = n.GetIntValue(); } },
                { "extendedStrikeTime", n => { ExtendedStrikeTime = n.GetIntValue(); } },
                { "heldTime", n => { HeldTime = n.GetIntValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "strikeTime", n => { StrikeTime = n.GetIntValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("activateStrikeOnRex", ActivateStrikeOnRex);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.DoorMode>("defaultDoorMode", DefaultDoorMode);
            writer.WriteBoolValue("devInitiatesConnection", DevInitiatesConnection);
            writer.WriteBoolValue("disableEncryption", DisableEncryption);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("encryptionKeyRef", EncryptionKeyRef);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("encryptionKeyRefNext", EncryptionKeyRefNext);
            writer.WriteIntValue("extendedHeldTime", ExtendedHeldTime);
            writer.WriteIntValue("extendedStrikeTime", ExtendedStrikeTime);
            writer.WriteIntValue("heldTime", HeldTime);
            writer.WriteStringValue("password", Password);
            writer.WriteIntValue("strikeTime", StrikeTime);
            writer.WriteStringValue("username", Username);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
