// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// An event.  An event is designed to contain all relevant data captured at the time of the event, to minimize the need to cross-reference with other data, and to include all information needed for reporting, filtering, viewing embedded within the event.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Evt : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether this event has been consumed or not.  This is a kind of &quot;soft&quot; delete (if consumed=true).</summary>
        public bool? Consumed { get; set; }
        /// <summary>Extra/arbitrary data associated with the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Data { get; set; }
#nullable restore
#else
        public string Data { get; set; }
#endif
        /// <summary>Time recorded in DB.</summary>
        public DateTimeOffset? DbTime { get; set; }
        /// <summary>An event code, indicating what happened.0 - DAEMON_STARTUP - Z9/FL=X startup.6 - LOGIN_GRANTED - Login granted (application access).7 - LOGIN_DENIED - Login denied (application access).8 - LOGOUT - Logout (application access).9 - CONTROLLER_STARTUP - Controller startup.10 - CONTROLLER_ONLINE - Controller online.11 - CONTROLLER_OFFLINE - Controller offline.15 - CRED_READER_ONLINE - Credential reader online.16 - CRED_READER_OFFLINE - Credential reader offline.17 - RAW_CRED_READ - Raw credential read.48 - DOOR_ACCESS_GRANTED - Door access granted.49 - DOOR_ACCESS_DENIED - Door access denied.52 - DOOR_FORCED - Door forced open.53 - DOOR_NOT_FORCED - Door not forced open.54 - DOOR_HELD - Door held open.55 - DOOR_NOT_HELD - Door not held open.56 - DOOR_OPENED - Door opened.57 - DOOR_CLOSED - Door closed.58 - DOOR_LOCKED - Door locked.59 - DOOR_UNLOCKED - Door unlocked.60 - DOOR_MODE_STATIC_STATE_UNLOCKED - Door mode - Unlocked - free access.61 - DOOR_MODE_STATIC_STATE_LOCKED - Door mode - No access.62 - DOOR_MODE_CARD_ONLY - Door mode - Card only.63 - DOOR_MODE_CARD_AND_CONFIRMING_PIN - Door mode - Card and PIN.64 - DOOR_MODE_UNIQUE_PIN_ONLY - Door mode - PIN only.65 - DOOR_MODE_CARD_ONLY_OR_UNIQUE_PIN - Door mode - Card or PIN.86 - EXIT_REQUESTED - Exit requested.87 - MOMENTARY_UNLOCK - Momentary unlock.113 - POWER_PRIMARY - On primary power.114 - POWER_OFF_PRIMARY - Off primary power.115 - POWER_NONE - No power.116 - BATTERY_OK - Battery OK.117 - BATTERY_LOW - Battery low.118 - BATTERY_FAIL - Battery fail.125 - TAMPER_NORMAL - Tamper normal (no tamper).126 - TAMPER - Tamper.127 - SCHED_ACTIVE - Schedule active.128 - SCHED_INACTIVE - Schedule inactive.153 - EXTERNAL - Externally defined.244 - BATTERY_CRITICAL - Battery critical.259 - CRED_READER_POWER_CYCLE - The CredReader has had its power cycled - for example an OSDP reader reporting the power status flag as active.</summary>
        public int? EvtCode { get; set; }
        /// <summary>A reference (really a summary) from an Evt to a Dev, containing its essential properties, and without requiring any lookup of the referenced object for reporting, filtering, or display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.EvtDevRef? EvtControllerRef { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.EvtDevRef EvtControllerRef { get; set; }
#endif
        /// <summary>A reference (really a summary) from an Evt to a Cred, containing its essential properties, and without requiring any lookup of the referenced object for reporting, filtering, or display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.EvtCredRef? EvtCredRef { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.EvtCredRef EvtCredRef { get; set; }
#endif
        /// <summary>A reference (really a summary) from an Evt to a Dev, containing its essential properties, and without requiring any lookup of the referenced object for reporting, filtering, or display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.EvtDevRef? EvtDevRef { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.EvtDevRef EvtDevRef { get; set; }
#endif
        /// <summary>Evt modifiers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.EvtModifiers? EvtModifiers { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.EvtModifiers EvtModifiers { get; set; }
#endif
        /// <summary>A reference (really a summary) from an Evt to a Sched, containing its essential properties, and without requiring any lookup of the referenced object for reporting, filtering, or display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.EvtSchedRef? EvtSchedRef { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.EvtSchedRef EvtSchedRef { get; set; }
#endif
        /// <summary>An Evt sub-code, to provide further granularity than EvtCode.0 - ACCESS_DENIED_INACTIVE - Access denied - inactive.6 - ACCESS_DENIED_NOT_EFFECTIVE - Access denied - not yet effective.7 - ACCESS_DENIED_EXPIRED - Access denied - expired.10 - ACCESS_DENIED_NO_PRIV - Access denied - no privileges.11 - ACCESS_DENIED_OUTSIDE_SCHED - Access denied - outside schedule.14 - ACCESS_DENIED_UNKNOWN_CRED_NUM - Access denied - unknown credential (card) number.15 - ACCESS_DENIED_UNKNOWN_CRED_NUM_FORMAT - Access denied - unknown credential (card) number format.17 - ACCESS_DENIED_UNKNOWN_CRED_UNIQUE_PIN - Access denied - unknown unique PIN.20 - ACCESS_DENIED_INCORRECT_FACILITY_CODE - Access denied - incorrect facility code.22 - ACCESS_DENIED_DOOR_MODE_STATIC_LOCKED - Access denied - door mode - static locked (no access).23 - ACCESS_DENIED_DOOR_MODE_DOESNT_ALLOW_CARD - Access denied - door mode - doesn&apos;t allow card.24 - ACCESS_DENIED_DOOR_MODE_DOESNT_ALLOW_UNIQUE_PIN - Access denied - door mode - doesn&apos;t allow unique PIN.25 - ACCESS_DENIED_NO_CONFIRMING_PIN_FOR_CRED - Access denied - no confirming PIN for credential.27 - ACCESS_DENIED_INCORRECT_CONFIRMING_PIN - Access denied - incorrect confirming PIN.104 - EXTERNAL - Externally defined.</summary>
        public int? EvtSubCode { get; set; }
        /// <summary>If evtCode is EvtCode.EXTERNAL, the external system&apos;s id for the external event code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalEvtCodeId { get; set; }
#nullable restore
#else
        public string ExternalEvtCodeId { get; set; }
#endif
        /// <summary>If evtCode is EvtCode.EXTERNAL, the text string for the external event code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalEvtCodeText { get; set; }
#nullable restore
#else
        public string ExternalEvtCodeText { get; set; }
#endif
        /// <summary>If evtSubCode is EvtSubCode.EXTERNAL, the external system&apos;s id for the external event sub code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalSubCodeId { get; set; }
#nullable restore
#else
        public string ExternalSubCodeId { get; set; }
#endif
        /// <summary>If evtSubCode is EvtSubCode.EXTERNAL, the text string for the external event sub-code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalSubCodeText { get; set; }
#nullable restore
#else
        public string ExternalSubCodeText { get; set; }
#endif
        /// <summary>Time occurred at hardware.</summary>
        public DateTimeOffset? HwTime { get; set; }
        /// <summary>The local time zone, for display purposes only, for displaying hwTime/hwTimeMillis.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HwTimeZone { get; set; }
#nullable restore
#else
        public string HwTimeZone { get; set; }
#endif
        /// <summary>Priority.  Lower numbers mean more important.  0 is the &quot;most important&quot;.</summary>
        public int? Priority { get; set; }
        /// <summary>Unique ID.</summary>
        public long? Unid { get; set; }
        /// <summary>UUID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.Evt"/> and sets the default values.
        /// </summary>
        public Evt()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.Evt"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.Evt CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.Evt();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "consumed", n => { Consumed = n.GetBoolValue(); } },
                { "data", n => { Data = n.GetStringValue(); } },
                { "dbTime", n => { DbTime = n.GetDateTimeOffsetValue(); } },
                { "evtCode", n => { EvtCode = n.GetIntValue(); } },
                { "evtControllerRef", n => { EvtControllerRef = n.GetObjectValue<global::Z9Flex.Client.Models.EvtDevRef>(global::Z9Flex.Client.Models.EvtDevRef.CreateFromDiscriminatorValue); } },
                { "evtCredRef", n => { EvtCredRef = n.GetObjectValue<global::Z9Flex.Client.Models.EvtCredRef>(global::Z9Flex.Client.Models.EvtCredRef.CreateFromDiscriminatorValue); } },
                { "evtDevRef", n => { EvtDevRef = n.GetObjectValue<global::Z9Flex.Client.Models.EvtDevRef>(global::Z9Flex.Client.Models.EvtDevRef.CreateFromDiscriminatorValue); } },
                { "evtModifiers", n => { EvtModifiers = n.GetObjectValue<global::Z9Flex.Client.Models.EvtModifiers>(global::Z9Flex.Client.Models.EvtModifiers.CreateFromDiscriminatorValue); } },
                { "evtSchedRef", n => { EvtSchedRef = n.GetObjectValue<global::Z9Flex.Client.Models.EvtSchedRef>(global::Z9Flex.Client.Models.EvtSchedRef.CreateFromDiscriminatorValue); } },
                { "evtSubCode", n => { EvtSubCode = n.GetIntValue(); } },
                { "externalEvtCodeId", n => { ExternalEvtCodeId = n.GetStringValue(); } },
                { "externalEvtCodeText", n => { ExternalEvtCodeText = n.GetStringValue(); } },
                { "externalSubCodeId", n => { ExternalSubCodeId = n.GetStringValue(); } },
                { "externalSubCodeText", n => { ExternalSubCodeText = n.GetStringValue(); } },
                { "hwTime", n => { HwTime = n.GetDateTimeOffsetValue(); } },
                { "hwTimeZone", n => { HwTimeZone = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "unid", n => { Unid = n.GetLongValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("consumed", Consumed);
            writer.WriteStringValue("data", Data);
            writer.WriteDateTimeOffsetValue("dbTime", DbTime);
            writer.WriteIntValue("evtCode", EvtCode);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.EvtDevRef>("evtControllerRef", EvtControllerRef);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.EvtCredRef>("evtCredRef", EvtCredRef);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.EvtDevRef>("evtDevRef", EvtDevRef);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.EvtModifiers>("evtModifiers", EvtModifiers);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.EvtSchedRef>("evtSchedRef", EvtSchedRef);
            writer.WriteIntValue("evtSubCode", EvtSubCode);
            writer.WriteStringValue("externalEvtCodeId", ExternalEvtCodeId);
            writer.WriteStringValue("externalEvtCodeText", ExternalEvtCodeText);
            writer.WriteStringValue("externalSubCodeId", ExternalSubCodeId);
            writer.WriteStringValue("externalSubCodeText", ExternalSubCodeText);
            writer.WriteDateTimeOffsetValue("hwTime", HwTime);
            writer.WriteStringValue("hwTimeZone", HwTimeZone);
            writer.WriteIntValue("priority", Priority);
            writer.WriteLongValue("unid", Unid);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
