// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// A reference (really a summary) from an Evt to a Dev, containing its essential properties, and without requiring any lookup of the referenced object for reporting, filtering, or display.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EvtDevRef : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>From referenced Dev - address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>Model for a Dev (device).0 - IO_CONTROLLER_Z9_CUSTOM - IO_CONTROLLER model - z9io - Custom.14 - SENSOR_DIGITAL - SENSOR model - digital.18 - ACTUATOR_DIGITAL - ACTUATOR model - digital.26 - IO_CONTROLLER_Z9_SPCORE - IO_CONTROLLER - Z9-Security SP-Core.46 - IO_CONTROLLER_EXTERNAL - Externally-defined - IO_CONTROLLER.164 - IO_CONTROLLER_COMMUNITY - IO_CONTROLLER model - Community.165 - IO_CONTROLLER_COMMUNITY_SUB - IO_CONTROLLER model - Community sub-controller.227 - CRED_READER_OSDP - CRED_READER model - OSDP (generic).259 - DOOR_COMMUNITY - DOOR model - Community.</summary>
        public int? DevMod { get; set; }
        /// <summary>Device hardware platform, or family, for a device model (DevMod) for a Dev.0 - Z9_SECURITY - Z9 Security, including Z9/Open and Z9/Flex.9 - EXTERNAL - External.11 - PKOC - PKOC.17 - COMMUNITY - Community.19 - PSIA - PSIA.</summary>
        public int? DevPlatform { get; set; }
        /// <summary>Device sub-type.7 - IO_CONTROLLER_SUB - IO_CONTROLLER - sub-controller.</summary>
        public int? DevSubType { get; set; }
        /// <summary>Type (subclass) of Dev (device).0 - NODE_DEV - Device representing a node, which is a server or service running the Z9/FL=X software.1 - IO_CONTROLLER - A controller, such as an access control panel.  It may be an intelligent controller, a downstream controller, or a virtual/placeholder controller.2 - SENSOR - Sensor (input), including door contact and REX inputs, AUX inputs, alarm inputs, environmental inputs, others.3 - ACTUATOR - Actuator (output), including relay outputs, AUX outputs, LED outputs, others.4 - CRED_READER - Credential reader.5 - DOOR - Access-control door (access point).</summary>
        public int? DevType { get; set; }
        /// <summary>Usage of a Dev.  This describes how the device is used, in other words, its function.0 - ACTUATOR_DOOR_STRIKE - ACTUATOR - door strike. HAS SEMANTICS.2 - ACTUATOR_CRED_READER_LED_RED - ACTUATOR - Cred reader LED - Red. HAS SEMANTICS.3 - ACTUATOR_CRED_READER_LED_GREEN - ACTUATOR - Cred reader LED - Green. HAS SEMANTICS.4 - ACTUATOR_CRED_READER_BEEPER - ACTUATOR - Cred reader beeper. HAS SEMANTICS.10 - SENSOR_DOOR_CONTACT - SENSOR - door contact. HAS SEMANTICS.11 - SENSOR_REX - SENSOR - REX (request to exit). HAS SEMANTICS.12 - SENSOR_TAMPER - SENSOR - Tamper. HAS SEMANTICS.13 - SENSOR_POWER - SENSOR - Power monitor. HAS SEMANTICS.14 - SENSOR_BATTERY - SENSOR - Battery monitor. HAS SEMANTICS.38 - CRED_READER_DOOR - CRED_READER - for a door.  HAS SEMANTICS.39 - DOOR_EXIT - DOOR - exit (as opposed to entry). HAS SEMANTICS.  Logical parent must be a DOOR.44 - IO_CONTROLLER_SECONDARY - IO_CONTROLLER - secondary. HAS SEMANTICS.</summary>
        public int? DevUse { get; set; }
        /// <summary>From referenced Dev - externalDevModId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalDevModId { get; set; }
#nullable restore
#else
        public string ExternalDevModId { get; set; }
#endif
        /// <summary>From referenced Dev - externalDevModText</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalDevModText { get; set; }
#nullable restore
#else
        public string ExternalDevModText { get; set; }
#endif
        /// <summary>From referenced Dev - externalDevTypeId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalDevTypeId { get; set; }
#nullable restore
#else
        public string ExternalDevTypeId { get; set; }
#endif
        /// <summary>From referenced Dev - externalDevTypeText</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalDevTypeText { get; set; }
#nullable restore
#else
        public string ExternalDevTypeText { get; set; }
#endif
        /// <summary>From referenced Dev - externalId</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>From referenced Dev - logicalAddress</summary>
        public int? LogicalAddress { get; set; }
        /// <summary>From referenced Dev - name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>From referenced Dev - tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>From referenced Dev - unid</summary>
        public int? Unid { get; set; }
        /// <summary>From referenced Dev - uuid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.EvtDevRef"/> and sets the default values.
        /// </summary>
        public EvtDevRef()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.EvtDevRef"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.EvtDevRef CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.EvtDevRef();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "devMod", n => { DevMod = n.GetIntValue(); } },
                { "devPlatform", n => { DevPlatform = n.GetIntValue(); } },
                { "devSubType", n => { DevSubType = n.GetIntValue(); } },
                { "devType", n => { DevType = n.GetIntValue(); } },
                { "devUse", n => { DevUse = n.GetIntValue(); } },
                { "externalDevModId", n => { ExternalDevModId = n.GetStringValue(); } },
                { "externalDevModText", n => { ExternalDevModText = n.GetStringValue(); } },
                { "externalDevTypeId", n => { ExternalDevTypeId = n.GetStringValue(); } },
                { "externalDevTypeText", n => { ExternalDevTypeText = n.GetStringValue(); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "logicalAddress", n => { LogicalAddress = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteIntValue("devMod", DevMod);
            writer.WriteIntValue("devPlatform", DevPlatform);
            writer.WriteIntValue("devSubType", DevSubType);
            writer.WriteIntValue("devType", DevType);
            writer.WriteIntValue("devUse", DevUse);
            writer.WriteStringValue("externalDevModId", ExternalDevModId);
            writer.WriteStringValue("externalDevModText", ExternalDevModText);
            writer.WriteStringValue("externalDevTypeId", ExternalDevTypeId);
            writer.WriteStringValue("externalDevTypeText", ExternalDevTypeText);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteIntValue("logicalAddress", LogicalAddress);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("tag", Tag);
            writer.WriteIntValue("unid", Unid);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
