// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// A holiday (element of a HolCal, which is a holiday calendar).  A.K.A &quot;special day&quot;.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Hol : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether this holiday is a member of all holiday types.</summary>
        public bool? AllHolTypes { get; set; }
        /// <summary>The date of the holiday.</summary>
        public Date? Date { get; set; }
        /// <summary>Reference to another object, including type, with all possible identity properties, as well as name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.ObjRef? HolCal { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.ObjRef HolCal { get; set; }
#endif
        /// <summary>Reference to (and &apos;type&apos; equals) - HolType</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Z9Flex.Client.Models.ObjRef>? HolTypes { get; set; }
#nullable restore
#else
        public List<global::Z9Flex.Client.Models.ObjRef> HolTypes { get; set; }
#endif
        /// <summary>Name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Number of days the holiday lasts (1 minimum).</summary>
        public int? NumDays { get; set; }
        /// <summary>Number of years to repeat. Null for indefinitely.</summary>
        public int? NumYearsRepeat { get; set; }
        /// <summary>If true, SchedDay is preserved on this holiday.</summary>
        public bool? PreserveSchedDay { get; set; }
        /// <summary>Whether the holiday repeats every year.</summary>
        public bool? Repeat { get; set; }
        /// <summary>tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>UUID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uuid { get; set; }
#nullable restore
#else
        public string Uuid { get; set; }
#endif
        /// <summary>Version (for optimistic locking)</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.Hol"/> and sets the default values.
        /// </summary>
        public Hol()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.Hol"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.Hol CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.Hol();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allHolTypes", n => { AllHolTypes = n.GetBoolValue(); } },
                { "date", n => { Date = n.GetDateValue(); } },
                { "holCal", n => { HolCal = n.GetObjectValue<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue); } },
                { "holTypes", n => { HolTypes = n.GetCollectionOfObjectValues<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "numDays", n => { NumDays = n.GetIntValue(); } },
                { "numYearsRepeat", n => { NumYearsRepeat = n.GetIntValue(); } },
                { "preserveSchedDay", n => { PreserveSchedDay = n.GetBoolValue(); } },
                { "repeat", n => { Repeat = n.GetBoolValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
                { "uuid", n => { Uuid = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allHolTypes", AllHolTypes);
            writer.WriteDateValue("date", Date);
            writer.WriteObjectValue<global::Z9Flex.Client.Models.ObjRef>("holCal", HolCal);
            writer.WriteCollectionOfObjectValues<global::Z9Flex.Client.Models.ObjRef>("holTypes", HolTypes);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("numDays", NumDays);
            writer.WriteIntValue("numYearsRepeat", NumYearsRepeat);
            writer.WriteBoolValue("preserveSchedDay", PreserveSchedDay);
            writer.WriteBoolValue("repeat", Repeat);
            writer.WriteStringValue("tag", Tag);
            writer.WriteIntValue("unid", Unid);
            writer.WriteStringValue("uuid", Uuid);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
