// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// Parity BinaryElement. - only applicable if type=1 (BinaryElementType_PARITY)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParityBinaryElement : global::Z9Flex.Client.Models.BinaryElement, IParsable
    {
        /// <summary>If null, then all bits included in parity calculation.  If not null, then this is a String of &apos;0&apos; and &apos;1&apos; ASCII characters representing the mask.  The mask must be the same length as srcLen.  It should not have 0s/1s for the other bits on the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mask { get; set; }
#nullable restore
#else
        public string Mask { get; set; }
#endif
        /// <summary>true if odd parity, false if even parity.</summary>
        public bool? Odd { get; set; }
        /// <summary>Length of the source of the parity. srcStart/srcLen does NOT include the parity bit itself.</summary>
        public int? SrcLen { get; set; }
        /// <summary>Starting bit for the source of the parity, zero-based.  srcStart/srcLen does NOT include the parity bit itself.</summary>
        public int? SrcStart { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.ParityBinaryElement"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Z9Flex.Client.Models.ParityBinaryElement CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.ParityBinaryElement();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "mask", n => { Mask = n.GetStringValue(); } },
                { "odd", n => { Odd = n.GetBoolValue(); } },
                { "srcLen", n => { SrcLen = n.GetIntValue(); } },
                { "srcStart", n => { SrcStart = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("mask", Mask);
            writer.WriteBoolValue("odd", Odd);
            writer.WriteIntValue("srcLen", SrcLen);
            writer.WriteIntValue("srcStart", SrcStart);
        }
    }
}
#pragma warning restore CS0618
