// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Z9Flex.Client.Models
{
    /// <summary>
    /// Element of a Sched.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SchedElement : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the element applies on holidays, in general.</summary>
        public bool? Holidays { get; set; }
        /// <summary>Reference to (and &apos;type&apos; equals) - HolType - If holidays is true, and this is an empty list, then all holiday types.  If holidays is true, and this list is not empty, then only the holiday types in the list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Z9Flex.Client.Models.ObjRef>? HolTypes { get; set; }
#nullable restore
#else
        public List<global::Z9Flex.Client.Models.ObjRef> HolTypes { get; set; }
#endif
        /// <summary>If set, the stopping time is the stopping time plus this many days.  This allows an interval to cross over midnight, or to span multiple days.  Not supported by all hardware.</summary>
        public int? PlusDays { get; set; }
        /// <summary>Which days the element applies on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? SchedDays { get; set; }
#nullable restore
#else
        public List<int?> SchedDays { get; set; }
#endif
        /// <summary>Starting time for the interval.</summary>
        public Time? Start { get; set; }
        /// <summary>Stopping time for the interval.</summary>
        public Time? Stop { get; set; }
        /// <summary>Unique ID.</summary>
        public int? Unid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Models.SchedElement"/> and sets the default values.
        /// </summary>
        public SchedElement()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.SchedElement"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.Models.SchedElement CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.Models.SchedElement();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "holTypes", n => { HolTypes = n.GetCollectionOfObjectValues<global::Z9Flex.Client.Models.ObjRef>(global::Z9Flex.Client.Models.ObjRef.CreateFromDiscriminatorValue)?.AsList(); } },
                { "holidays", n => { Holidays = n.GetBoolValue(); } },
                { "plusDays", n => { PlusDays = n.GetIntValue(); } },
                { "schedDays", n => { SchedDays = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "start", n => { Start = n.GetTimeValue(); } },
                { "stop", n => { Stop = n.GetTimeValue(); } },
                { "unid", n => { Unid = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("holidays", Holidays);
            writer.WriteCollectionOfObjectValues<global::Z9Flex.Client.Models.ObjRef>("holTypes", HolTypes);
            writer.WriteIntValue("plusDays", PlusDays);
            writer.WriteCollectionOfPrimitiveValues<int?>("schedDays", SchedDays);
            writer.WriteTimeValue("start", Start);
            writer.WriteTimeValue("stop", Stop);
            writer.WriteIntValue("unid", Unid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
