// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Z9Flex.Client.Evt.List;
using Z9Flex.Client.Evt.Show;
namespace Z9Flex.Client.Evt
{
    /// <summary>
    /// Builds and executes requests for operations under \evt
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EvtRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The list property</summary>
        public global::Z9Flex.Client.Evt.List.ListRequestBuilder List
        {
            get => new global::Z9Flex.Client.Evt.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The show property</summary>
        public global::Z9Flex.Client.Evt.Show.ShowRequestBuilder Show
        {
            get => new global::Z9Flex.Client.Evt.Show.ShowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Evt.EvtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EvtRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/evt", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Evt.EvtRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EvtRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/evt", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
