// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Z9Flex.Client.Models;
namespace Z9Flex.Client.HolCal.Update.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \holCal\update\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/holCal/update/{id}{?upsert*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/holCal/update/{id}{?upsert*}", rawUrl)
        {
        }
        /// <summary>
        /// Update HolCal
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.HolCal.Update.Item.UpdatePostResponse"/></returns>
        /// <param name="body">Holiday calendar, consisting of multiple holidays (Hol).</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Z9Flex.Client.HolCal.Update.Item.UpdatePostResponse?> PostAsUpdatePostResponseAsync(global::Z9Flex.Client.Models.HolCal body, Action<RequestConfiguration<global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder.UpdateItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Z9Flex.Client.HolCal.Update.Item.UpdatePostResponse> PostAsUpdatePostResponseAsync(global::Z9Flex.Client.Models.HolCal body, Action<RequestConfiguration<global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder.UpdateItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Z9Flex.Client.HolCal.Update.Item.UpdatePostResponse>(requestInfo, global::Z9Flex.Client.HolCal.Update.Item.UpdatePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update HolCal
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.HolCal.Update.Item.UpdateResponse"/></returns>
        /// <param name="body">Holiday calendar, consisting of multiple holidays (Hol).</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsUpdatePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Z9Flex.Client.HolCal.Update.Item.UpdateResponse?> PostAsync(global::Z9Flex.Client.Models.HolCal body, Action<RequestConfiguration<global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder.UpdateItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Z9Flex.Client.HolCal.Update.Item.UpdateResponse> PostAsync(global::Z9Flex.Client.Models.HolCal body, Action<RequestConfiguration<global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder.UpdateItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Z9Flex.Client.HolCal.Update.Item.UpdateResponse>(requestInfo, global::Z9Flex.Client.HolCal.Update.Item.UpdateResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update HolCal
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Holiday calendar, consisting of multiple holidays (Hol).</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Z9Flex.Client.Models.HolCal body, Action<RequestConfiguration<global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder.UpdateItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Z9Flex.Client.Models.HolCal body, Action<RequestConfiguration<global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder.UpdateItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Update HolCal
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateItemRequestBuilderPostQueryParameters 
        {
            /// <summary>defaults to false.  If true, upsert is performed (if the referenced object does not exist).  Only valid by UUID.</summary>
            [QueryParameter("upsert")]
            public bool? Upsert { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateItemRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Z9Flex.Client.HolCal.Update.Item.UpdateItemRequestBuilder.UpdateItemRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
