// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Z9Flex.Client.Hol.Delete.Item;
namespace Z9Flex.Client.Hol.Delete
{
    /// <summary>
    /// Builds and executes requests for operations under \hol\delete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Z9Flex.Client.hol.delete.item collection</summary>
        /// <param name="position">Numeric unid, or string UUID, of the Hol</param>
        /// <returns>A <see cref="global::Z9Flex.Client.Hol.Delete.Item.DeleteItemRequestBuilder"/></returns>
        public global::Z9Flex.Client.Hol.Delete.Item.DeleteItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Z9Flex.Client.Hol.Delete.Item.DeleteItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Hol.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hol/delete", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Hol.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hol/delete", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
