// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Z9Flex.Client.Actuator;
using Z9Flex.Client.Authenticate;
using Z9Flex.Client.BasicDataLayout;
using Z9Flex.Client.BinaryFormat;
using Z9Flex.Client.Controller;
using Z9Flex.Client.Cred;
using Z9Flex.Client.CredReader;
using Z9Flex.Client.CredTemplate;
using Z9Flex.Client.DataFormat;
using Z9Flex.Client.DataLayout;
using Z9Flex.Client.Dev;
using Z9Flex.Client.DevStateRecord;
using Z9Flex.Client.Door;
using Z9Flex.Client.DoorAccessPriv;
using Z9Flex.Client.EncryptionKey;
using Z9Flex.Client.Evt;
using Z9Flex.Client.Hol;
using Z9Flex.Client.HolCal;
using Z9Flex.Client.HolType;
using Z9Flex.Client.JsonEscaped;
using Z9Flex.Client.NodeDev;
using Z9Flex.Client.Sched;
using Z9Flex.Client.Sensor;
using Z9Flex.Client.Terminate;
namespace Z9Flex.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FlexClient : BaseRequestBuilder
    {
        /// <summary>The actuator property</summary>
        public global::Z9Flex.Client.Actuator.ActuatorRequestBuilder Actuator
        {
            get => new global::Z9Flex.Client.Actuator.ActuatorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The authenticate property</summary>
        public global::Z9Flex.Client.Authenticate.AuthenticateRequestBuilder Authenticate
        {
            get => new global::Z9Flex.Client.Authenticate.AuthenticateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The basicDataLayout property</summary>
        public global::Z9Flex.Client.BasicDataLayout.BasicDataLayoutRequestBuilder BasicDataLayout
        {
            get => new global::Z9Flex.Client.BasicDataLayout.BasicDataLayoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The binaryFormat property</summary>
        public global::Z9Flex.Client.BinaryFormat.BinaryFormatRequestBuilder BinaryFormat
        {
            get => new global::Z9Flex.Client.BinaryFormat.BinaryFormatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The controller property</summary>
        public global::Z9Flex.Client.Controller.ControllerRequestBuilder Controller
        {
            get => new global::Z9Flex.Client.Controller.ControllerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cred property</summary>
        public global::Z9Flex.Client.Cred.CredRequestBuilder Cred
        {
            get => new global::Z9Flex.Client.Cred.CredRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credReader property</summary>
        public global::Z9Flex.Client.CredReader.CredReaderRequestBuilder CredReader
        {
            get => new global::Z9Flex.Client.CredReader.CredReaderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credTemplate property</summary>
        public global::Z9Flex.Client.CredTemplate.CredTemplateRequestBuilder CredTemplate
        {
            get => new global::Z9Flex.Client.CredTemplate.CredTemplateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dataFormat property</summary>
        public global::Z9Flex.Client.DataFormat.DataFormatRequestBuilder DataFormat
        {
            get => new global::Z9Flex.Client.DataFormat.DataFormatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dataLayout property</summary>
        public global::Z9Flex.Client.DataLayout.DataLayoutRequestBuilder DataLayout
        {
            get => new global::Z9Flex.Client.DataLayout.DataLayoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dev property</summary>
        public global::Z9Flex.Client.Dev.DevRequestBuilder Dev
        {
            get => new global::Z9Flex.Client.Dev.DevRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devStateRecord property</summary>
        public global::Z9Flex.Client.DevStateRecord.DevStateRecordRequestBuilder DevStateRecord
        {
            get => new global::Z9Flex.Client.DevStateRecord.DevStateRecordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The door property</summary>
        public global::Z9Flex.Client.Door.DoorRequestBuilder Door
        {
            get => new global::Z9Flex.Client.Door.DoorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The doorAccessPriv property</summary>
        public global::Z9Flex.Client.DoorAccessPriv.DoorAccessPrivRequestBuilder DoorAccessPriv
        {
            get => new global::Z9Flex.Client.DoorAccessPriv.DoorAccessPrivRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The encryptionKey property</summary>
        public global::Z9Flex.Client.EncryptionKey.EncryptionKeyRequestBuilder EncryptionKey
        {
            get => new global::Z9Flex.Client.EncryptionKey.EncryptionKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The evt property</summary>
        public global::Z9Flex.Client.Evt.EvtRequestBuilder Evt
        {
            get => new global::Z9Flex.Client.Evt.EvtRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hol property</summary>
        public global::Z9Flex.Client.Hol.HolRequestBuilder Hol
        {
            get => new global::Z9Flex.Client.Hol.HolRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The holCal property</summary>
        public global::Z9Flex.Client.HolCal.HolCalRequestBuilder HolCal
        {
            get => new global::Z9Flex.Client.HolCal.HolCalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The holType property</summary>
        public global::Z9Flex.Client.HolType.HolTypeRequestBuilder HolType
        {
            get => new global::Z9Flex.Client.HolType.HolTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The json property</summary>
        public global::Z9Flex.Client.JsonEscaped.JsonRequestBuilder Json
        {
            get => new global::Z9Flex.Client.JsonEscaped.JsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nodeDev property</summary>
        public global::Z9Flex.Client.NodeDev.NodeDevRequestBuilder NodeDev
        {
            get => new global::Z9Flex.Client.NodeDev.NodeDevRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sched property</summary>
        public global::Z9Flex.Client.Sched.SchedRequestBuilder Sched
        {
            get => new global::Z9Flex.Client.Sched.SchedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sensor property</summary>
        public global::Z9Flex.Client.Sensor.SensorRequestBuilder Sensor
        {
            get => new global::Z9Flex.Client.Sensor.SensorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terminate property</summary>
        public global::Z9Flex.Client.Terminate.TerminateRequestBuilder Terminate
        {
            get => new global::Z9Flex.Client.Terminate.TerminateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.FlexClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FlexClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
