// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Z9Flex.Client.Sensor.Delete;
using Z9Flex.Client.Sensor.List;
using Z9Flex.Client.Sensor.Save;
using Z9Flex.Client.Sensor.Update;
namespace Z9Flex.Client.Sensor
{
    /// <summary>
    /// Builds and executes requests for operations under \sensor
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SensorRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deletePath property</summary>
        public global::Z9Flex.Client.Sensor.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Z9Flex.Client.Sensor.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Z9Flex.Client.Sensor.List.ListRequestBuilder List
        {
            get => new global::Z9Flex.Client.Sensor.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The save property</summary>
        public global::Z9Flex.Client.Sensor.Save.SaveRequestBuilder Save
        {
            get => new global::Z9Flex.Client.Sensor.Save.SaveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Z9Flex.Client.Sensor.Update.UpdateRequestBuilder Update
        {
            get => new global::Z9Flex.Client.Sensor.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Sensor.SensorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SensorRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sensor", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.Sensor.SensorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SensorRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sensor", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
