// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Z9Flex.Client.Models;
namespace Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock
{
    /// <summary>
    /// Builds and executes requests for operations under \json\doorMomentaryUnlock
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DoorMomentaryUnlockRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DoorMomentaryUnlockRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/json/doorMomentaryUnlock{?extDoorTime*,heldPreAlarmWarnTime*,heldTime*,strikeTime*,tag*,unid*,uuid*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DoorMomentaryUnlockRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/json/doorMomentaryUnlock{?extDoorTime*,heldPreAlarmWarnTime*,heldTime*,strikeTime*,tag*,unid*,uuid*}", rawUrl)
        {
        }
        /// <summary>
        /// Controller: resync
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.VoidObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Z9Flex.Client.Models.VoidObject?> GetAsync(Action<RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder.DoorMomentaryUnlockRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Z9Flex.Client.Models.VoidObject> GetAsync(Action<RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder.DoorMomentaryUnlockRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Z9Flex.Client.Models.VoidObject>(requestInfo, global::Z9Flex.Client.Models.VoidObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Controller: resync
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder.DoorMomentaryUnlockRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder.DoorMomentaryUnlockRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Controller: resync
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DoorMomentaryUnlockRequestBuilderGetQueryParameters 
        {
            /// <summary>Use extended door times</summary>
            [QueryParameter("extDoorTime")]
            public bool? ExtDoorTime { get; set; }
            /// <summary>Held pre-alarm warning time</summary>
            [QueryParameter("heldPreAlarmWarnTime")]
            public int? HeldPreAlarmWarnTime { get; set; }
            /// <summary>Held time</summary>
            [QueryParameter("heldTime")]
            public int? HeldTime { get; set; }
            /// <summary>Strike time</summary>
            [QueryParameter("strikeTime")]
            public int? StrikeTime { get; set; }
            /// <summary>Device tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tag")]
            public string? Tag { get; set; }
#nullable restore
#else
            [QueryParameter("tag")]
            public string Tag { get; set; }
#endif
            /// <summary>Device unique ID</summary>
            [QueryParameter("unid")]
            public int? Unid { get; set; }
            /// <summary>Device UUID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("uuid")]
            public string? Uuid { get; set; }
#nullable restore
#else
            [QueryParameter("uuid")]
            public string Uuid { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DoorMomentaryUnlockRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder.DoorMomentaryUnlockRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
