// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
using Z9Flex.Client.Models;
namespace Z9Flex.Client.BasicDataLayout.Save
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SavePostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Data layout of DataFormat on a Cred.  This is most meaningful for smart cards (SmartDataLayout), which can have multiple files/sectors/blocks of data, protected by keys.  ANSI/ISO ABA Track II Magnetic stripe and non-smart-card proximity/RFID cards (binary/Wiegand) use the subclass BasicDataLayout, which simply has a single DataFormat, corresponding to all the data on the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Z9Flex.Client.Models.DataLayout? Instance { get; set; }
#nullable restore
#else
        public global::Z9Flex.Client.Models.DataLayout Instance { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.BasicDataLayout.Save.SavePostResponse"/> and sets the default values.
        /// </summary>
        public SavePostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.BasicDataLayout.Save.SavePostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Z9Flex.Client.BasicDataLayout.Save.SavePostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Z9Flex.Client.BasicDataLayout.Save.SavePostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "instance", n => { Instance = n.GetObjectValue<global::Z9Flex.Client.Models.DataLayout>(global::Z9Flex.Client.Models.DataLayout.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Z9Flex.Client.Models.DataLayout>("instance", Instance);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
