// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Z9Flex.Client.DoorAccessPriv.Show.Item;
namespace Z9Flex.Client.DoorAccessPriv.Show
{
    /// <summary>
    /// Builds and executes requests for operations under \doorAccessPriv\show
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShowRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Z9Flex.Client.doorAccessPriv.show.item collection</summary>
        /// <param name="position">Numeric unid, or string UUID, of the Priv</param>
        /// <returns>A <see cref="global::Z9Flex.Client.DoorAccessPriv.Show.Item.ShowItemRequestBuilder"/></returns>
        public global::Z9Flex.Client.DoorAccessPriv.Show.Item.ShowItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Z9Flex.Client.DoorAccessPriv.Show.Item.ShowItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.DoorAccessPriv.Show.ShowRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShowRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/doorAccessPriv/show", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.DoorAccessPriv.Show.ShowRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShowRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/doorAccessPriv/show", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
