// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Z9Flex.Client.JsonEscaped.DoorModeChange;
using Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock;
namespace Z9Flex.Client.JsonEscaped
{
    /// <summary>
    /// Builds and executes requests for operations under \json
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JsonRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The doorModeChange property</summary>
        public global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder DoorModeChange
        {
            get => new global::Z9Flex.Client.JsonEscaped.DoorModeChange.DoorModeChangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The doorMomentaryUnlock property</summary>
        public global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder DoorMomentaryUnlock
        {
            get => new global::Z9Flex.Client.JsonEscaped.DoorMomentaryUnlock.DoorMomentaryUnlockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.JsonEscaped.JsonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JsonRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/json", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.JsonEscaped.JsonRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JsonRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/json", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
