// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Z9Flex.Client.HolType.Delete;
using Z9Flex.Client.HolType.List;
using Z9Flex.Client.HolType.Save;
using Z9Flex.Client.HolType.Show;
using Z9Flex.Client.HolType.Update;
namespace Z9Flex.Client.HolType
{
    /// <summary>
    /// Builds and executes requests for operations under \holType
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HolTypeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deletePath property</summary>
        public global::Z9Flex.Client.HolType.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Z9Flex.Client.HolType.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Z9Flex.Client.HolType.List.ListRequestBuilder List
        {
            get => new global::Z9Flex.Client.HolType.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The save property</summary>
        public global::Z9Flex.Client.HolType.Save.SaveRequestBuilder Save
        {
            get => new global::Z9Flex.Client.HolType.Save.SaveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The show property</summary>
        public global::Z9Flex.Client.HolType.Show.ShowRequestBuilder Show
        {
            get => new global::Z9Flex.Client.HolType.Show.ShowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Z9Flex.Client.HolType.Update.UpdateRequestBuilder Update
        {
            get => new global::Z9Flex.Client.HolType.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.HolType.HolTypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HolTypeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/holType", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.HolType.HolTypeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HolTypeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/holType", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
