// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Z9Flex.Client.Models;
namespace Z9Flex.Client.CredReader.List
{
    /// <summary>
    /// Builds and executes requests for operations under \credReader\list
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.CredReader.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credReader/list{?devModRestriction%2EdevMods*,devUseRestriction%2EdevUses*,max*,offset*,order*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Z9Flex.Client.CredReader.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credReader/list{?devModRestriction%2EdevMods*,devUseRestriction%2EdevUses*,max*,offset*,order*}", rawUrl)
        {
        }
        /// <summary>
        /// List CredReader
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.Models.DevListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Z9Flex.Client.Models.DevListResponse?> GetAsync(Action<RequestConfiguration<global::Z9Flex.Client.CredReader.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Z9Flex.Client.Models.DevListResponse> GetAsync(Action<RequestConfiguration<global::Z9Flex.Client.CredReader.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Z9Flex.Client.Models.DevListResponse>(requestInfo, global::Z9Flex.Client.Models.DevListResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List CredReader
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Z9Flex.Client.CredReader.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Z9Flex.Client.CredReader.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Z9Flex.Client.CredReader.List.ListRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Z9Flex.Client.CredReader.List.ListRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Z9Flex.Client.CredReader.List.ListRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List CredReader
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListRequestBuilderGetQueryParameters 
        {
            /// <summary>DevModRestriction DevMod value(s)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("devModRestriction%2EdevMods")]
            public int?[]? DevModRestrictionDevMods { get; set; }
#nullable restore
#else
            [QueryParameter("devModRestriction%2EdevMods")]
            public int?[] DevModRestrictionDevMods { get; set; }
#endif
            /// <summary>DevUseRestriction DevUse value(s)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("devUseRestriction%2EdevUses")]
            public int?[]? DevUseRestrictionDevUses { get; set; }
#nullable restore
#else
            [QueryParameter("devUseRestriction%2EdevUses")]
            public int?[] DevUseRestrictionDevUses { get; set; }
#endif
            /// <summary>Maximum number of results to return</summary>
            [QueryParameter("max")]
            public int? Max { get; set; }
            /// <summary>Offset of the first result to return. Defaults to 0 if not present.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>Whether to order ascending or descending</summary>
            [Obsolete("This property is deprecated, use OrderAsGetOrderQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>Whether to order ascending or descending</summary>
            [QueryParameter("order")]
            public global::Z9Flex.Client.CredReader.List.GetOrderQueryParameterType? OrderAsGetOrderQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Z9Flex.Client.CredReader.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
